### ISSUE TITLE
LV2 plugin target via JUCE fork?

### ISSUE THREAD

**Issue by mxmilkiib** [vitling/crypt#4]
Hi, there are two JUCE forks with the additional target of [LV2](https://github.com/lv2/lv2/wiki) plugins; https://github.com/lv2-porting-project/JUCE/tree/lv2 and https://github.com/DISTRHO/JUCE. Recent ports they have been used for include [ChowMatrix](https://github.com/Chowdhury-DSP/ChowMatrix), [Vital[ium]](https://kx.studio/News/?action=view&url=kxstudio-monthly-report-february-2021) and [vmpc-juce](https://github.com/izzyreal/vmpc-juce). I was wondering if you might be interested in joining in?

There's no README on the exact process yet, and falktx uses make over cmake, but related information can be found in issues such as https://github.com/jatinchowdhury18/AnalogTapeModel/issues/7 https://github.com/izzyreal/vmpc-juce/issues/19 with on-going discussion in https://github.com/benthevining/imogen/issues/8

**Comment by benthevining** [comment]
If anyone involved with this whole Juce-forking-LV2-porting movement would be inclined to write a simple set of bullet-pointed steps on exactly *how* to integrate this to our existing CMake Juce build systems (or, even better, an example shell script that executes the entire build...), that would be very greatly appreciated. I haven’t yet found a single Juce fork that includes so much as an edited Readme...

I really am interested in supporting the LV2 format in my projects. I believe in open source formats, and am willing to do what I can to promote them. To me, it seems a slight shame that there is such abundance of LV2 advocates eager to ask plug-in developers to support their format, and so few who actually seem to want to explain how to use the tools they have built...

**Comment by vitling** [comment]
The CMake/build targets/plugin formats/building for different operating systems etc. part of the plugin development process is the part I understand the least about, and it's also the least fun for me. I'm very happy to stop when I have a plugin that can be used by the majority of people making music with host software.
Of course it's even better to support more plugin types, especially free-software targets, but it's not where I want to focus my personal development effort right now. However, I'd be happy to consider a pull request for this as long as: it doesn't impact the existing build targets, the use of a fork doesn't affect the licensing situation, and also that it would be relatively straightforward to revert to the main JUCE branch should the fork become stale in the future and fall behind.

**Comment by benthevining** [comment]
My thoughts almost exactly, well said 🙂

**Comment by jatinchowdhury18** [comment]
> If anyone involved with this whole Juce-forking-LV2-porting movement would be inclined to write a simple set of bullet-pointed steps on exactly how to integrate this to our existing CMake Juce build systems (or, even better, an example shell script that executes the entire build...), that would be very greatly appreciated.

@mxmilkiib has encouraged me to write up something like this, so [here it is](https://jatinchowdhury18.medium.com/building-lv2-plugins-with-juce-and-cmake-d1f8937dbac3) (I give some explanation of the context, and then the bullet points are closer to the bottom).

Anyway, I hope this can be useful in some way!

**Comment by benthevining** [comment]
Awesome!! I was meaning to write up something like this, but this looks great! Thank you for doing this!

**Comment by dromer** [comment]
JUCE7 preview includes LV2 support, so likely if/when you move to it you can get LV2 for free ;)
